blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/fellipeutaka/kanpeki/discussions/new?category=general
    about: If you can't get something to work the way you expect, open a question in our discussion forums.