import { exec } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import { rimraf } from "rimraf";
import { registrySchema } from "shadcn/schema";
import { registry } from "~/registry/registry";

const parsedRegistry = registrySchema.parse(registry);

async function buildRegistryIndex() {
  let index = `// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import { lazy } from "react";

export const Index: Record<string, any> = {`;
  for (const item of parsedRegistry.items) {
    if (!item.files) {
      continue;
    }

    const componentPath = item.files?.[0]?.path
      ? `~/${item.files[0].path.replace("src/", "")}`
      : "";

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${item.files?.map((file) => {
      const filePath = `${typeof file === "string" ? file : file.path}`;
      const resolvedFilePath = path.resolve(filePath);
      return typeof file === "string"
        ? `"${resolvedFilePath}"`
        : `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ""}"
    }`;
    })}],
    component: ${
      componentPath
        ? `lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "${item.name}"
      return { default: mod.default || mod[exportName] }
    })`
        : "null"
    },
    categories: ${JSON.stringify(item.categories)},
    meta: ${JSON.stringify(item.meta)},
  },`;
  }

  index += `
  }`;

  console.info(`#️⃣  ${Object.keys(parsedRegistry.items).length} items found`);

  // Write style index.
  rimraf.sync(path.join(process.cwd(), "src/registry/__index__.tsx"));
  await fs.writeFile(
    path.join(process.cwd(), "src/registry/__index__.tsx"),
    index
  );
}

async function buildRegistryJsonFile() {
  const registryJsonPath = path.join(process.cwd(), "registry.json");
  // 2. Write the content of the registry to `registry.json`
  rimraf.sync(registryJsonPath);
  await fs.writeFile(registryJsonPath, JSON.stringify(parsedRegistry, null, 2));

  // 3. Format the registry.json file.

  // 3. Copy the registry.json to the www/public/r directory.
  await fs.cp(
    path.join(process.cwd(), "registry.json"),
    path.join(process.cwd(), "../www/public/r/registry.json"),
    { recursive: true }
  );
}

function buildRegistry() {
  return new Promise<void>((resolve, reject) => {
    const process = exec("bun shadcn build");

    process.on("exit", (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Process exited with code ${code}`));
      }
    });
  });
}

try {
  console.info("📁 Building src/registry/__index__.tsx...");
  await buildRegistryIndex();

  console.info("💅 Building registry.json...");
  await buildRegistryJsonFile();

  console.info("🧱 Building registry");
  await buildRegistry();
} catch (error) {
  console.error(error);
  process.exit(1);
}
